### ISSUE TITLE
Bad links on Team page

### ISSUE THREAD

**Issue by lajanda** [threat-defuser/threat-defuser.org#16]
Two links on Team page go to 404 now (although they were ok before...)
Here are the correct links:
Tore Nesset is:
https://uit.no/ansatte/person?p_document_id=41533
Holger Pötzsch is:
https://uit.no/ansatte/person?p_document_id=43820

**Comment by bast** [comment]
I am looking at it ...

**Comment by bast** [comment]
UiT changed something? Anyway fix incoming ...
