### ISSUE TITLE
Attached file for upload

### ISSUE THREAD

**Issue by lajanda** [threat-defuser/threat-defuser.org#22]
[How to register publications and other activities.docx](https://github.com/threat-defuser/threat-defuser.org/files/5245097/How.to.register.publications.and.other.activities.docx)
I would like to upload this file but it seems that I don't have authority to upload files, so I have attached it instead. I will also add some code to the Resources page so that team members can link to this document. Thanks!

**Comment by bast** [comment]
Is it OK if I upload this as markdown document rather? These are much easier to work with in the Git(Hub) context. If you agree, then I can do it.

**Comment by lajanda** [comment]
Oh, I apologize, I should have thought of that. Of course. I will try to do better in the future. Markdown is always better than Microsoft.
            --laura
