### ISSUE TITLE
Add portraits to team

### ISSUE THREAD

**Issue by lajanda** [threat-defuser/threat-defuser.org#57]
Please add these pictures to the team page for: 
Isabel Dineen
Mariia Kobzeva
Valentina Zhukova
Anna Obukhova

Please also add:
Link for Mariia Kobzeva:
https://en.uit.no/ansatte/person?p_document_id=649306

Links for Dineen, Zhukova, and Obukhova can be added later (when their UiT links are established).

![dineen](https://user-images.githubusercontent.com/26918586/110605812-caed8b00-8189-11eb-8649-a63d7406be69.jpg)
![kobzeva](https://user-images.githubusercontent.com/26918586/110605821-cd4fe500-8189-11eb-95c6-b4b390bfbb91.jpg)
![zhukova](https://user-images.githubusercontent.com/26918586/110605834-d2149900-8189-11eb-9895-52673fcd7af8.jpg)
![obukhova](https://user-images.githubusercontent.com/26918586/110605991-038d6480-818a-11eb-8c19-fe636df0d244.jpg)

**Comment by bast** [comment]
Will do ASAP.
