### ISSUE TITLE
Add new team member

### ISSUE THREAD

**Issue by lajanda** [threat-defuser/threat-defuser.org#64]
Please add Jakub M. Godzimirski to the Team page. Here is his link and his portrait is attached. Thanks!
![2014 Jakub Godzimirski-portrett nettsider](https://user-images.githubusercontent.com/26918586/117132018-8a357b00-ada2-11eb-8231-938bafb461e1.jpg)

https://www.nupi.no/en/About-NUPI/Employees/Researchers/Jakub-M.-Godzimirski

**Comment by bast** [comment]
Thanks, I will take care of it today.
